version: '3.8'

services:
  app:
    image: ihmily/douyin-live-recorder:latest
    environment:
      - TERM=xterm-256color
    tty: true
    stdin_open: true
    #build: .
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./backup_config:/app/backup_config
      - ./downloads:/app/downloads
    restart: always